name: build upload artifacts

on:
  workflow_dispatch:
  
       
jobs:     
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:     
      version_number: ${{ steps.semver1.outputs.version }}
    steps:
      - name: checkout
        uses: actions/checkout@v4                 
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: mvn clean package      
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: target/web-app-1.1.1-SNAPSHOT.jar

      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v4
        with:
          settings-file: ./.mvn/local-settings.xml
          ignore-maven-wrapper: true
      
      - name: 'print version'
        run: |
         echo ${{ steps.semver1.outputs.version }}
    
    
 
        
